CREATE DATABASE vendedores;

use vendedores;

CREATE TABLE ciudad(
ID int IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50)
);

CREATE table vendedor(
ID int IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
DOCUMENTO	VARCHAR(11),
CIUDAD INT,
FOREIGN KEY(CIUDAD) REFERENCES CIUDAD (ID)
);


Registros de Pruebas
INSERT INTO vendedores.dbo.ciudad (ID, NOMBRE) VALUES(1, 'BOGOTA');
INSERT INTO vendedores.dbo.ciudad (ID, NOMBRE) VALUES(2, 'MEDELLIN');
INSERT INTO vendedores.dbo.ciudad (ID, NOMBRE) VALUES(3, 'CALI');
INSERT INTO vendedores.dbo.ciudad (ID, NOMBRE) VALUES(4, 'IBAGUE');

INSERT INTO vendedores.dbo.vendedor (NOMBRE,APELLIDO,DOCUMENTO,CIUDAD) VALUES ('ALEXIS','ROZO','14136457',2);
